### ISSUE TITLE
Add screw-holes on the corners of the bottom PCB for standoffs/feet

### ISSUE THREAD

**Issue by mcginty** [bschwind/key-ripper#22]
An example setup I like from my previous keyboard: they have some pads, with an optional "tilt" screwhole spots for a higher raised feet set on the back.

![1A64EADA-7DC2-4A0B-9C6C-B21BF144B9F9-4568-000001421729421F](https://user-images.githubusercontent.com/373823/194443761-f7454044-22bb-4639-b610-632d4ceeae5a.jpg)
![E756500D-248C-443D-88AE-CAC371F0B7CF-4568-000001421B3CDBDC](https://user-images.githubusercontent.com/373823/194443763-ec203352-1edc-4452-8cef-dbdd638edd8d.jpg)

Having some screw-in feet that are interchangeable/adjustable would be super lovely.

**Comment by bschwind** [comment]
Implemented by 14b9a9be80fa695a1f35e55d81ed551870d70178
